"""Paste transcribed text into the focused app.

All PyObjC calls are confined to the thin `_seams` block below. PyObjC's lazy
attribute loading can't be monkeypatched (it aborts the interpreter), so every
framework call goes through a plain Python function that tests can replace.
"""

import logging
import time
from AppKit import (
    NSPasteboard,
    NSPasteboardItem,
    NSPasteboardTypeString,
    NSWorkspace,
)
import HIServices
import Quartz


# Roles where we KNOW paste won't work (no text input)
_NON_TEXT_ROLES = {"AXWebArea", "AXImage", "AXGroup", "AXToolbar", "AXMenuBar",
                   "AXScrollArea", "AXSplitGroup", "AXTable", "AXOutline"}

# Mark clipboard entries as transient so clipboard managers (Maccy, Paste,
# etc.) ignore them.  See http://nspasteboard.org/
# ConcealedType is deliberately NOT set: it means "password", which would be a
# lie for a dictation transcript and would hide it from the user's own history.
_TRANSIENT_TYPE = "org.nspasteboard.TransientType"
_AUTOGENERATED_TYPE = "org.nspasteboard.AutoGeneratedType"

# Modifier flags that turn a bare Cmd+V into something else (Cmd+Opt+V etc.).
_MODIFIER_MASK = (
    Quartz.kCGEventFlagMaskCommand
    | Quartz.kCGEventFlagMaskControl
    | Quartz.kCGEventFlagMaskAlternate
    | Quartz.kCGEventFlagMaskShift
    | Quartz.kCGEventFlagMaskSecondaryFn
)

_V_KEYCODE = 9

# inject_text outcomes. The caller needs the reason, not just success/failure:
# "text is in your clipboard" is an actively wrong thing to tell someone whose
# transcript was withheld from a password field.
PASTED = "pasted"                  # pasted, clipboard restored
LEFT_IN_CLIPBOARD = "clipboard"    # no text field — text left for manual paste
FOCUS_CHANGED = "focus_changed"    # target app changed — text left for manual paste
REFUSED_SECURE = "secure_field"    # password field — nothing pasted, nothing copied


# --- PyObjC seams -----------------------------------------------------------


def _general_pasteboard():
    return NSPasteboard.generalPasteboard()


def _new_pasteboard_item():
    return NSPasteboardItem.alloc().init()


def _frontmost_app():
    return NSWorkspace.sharedWorkspace().frontmostApplication()


def _ax_value(element, attribute):
    """Read an AX attribute. Returns `(err, value)`; err 0 means success."""
    return HIServices.AXUIElementCopyAttributeValue(element, attribute, None)


def _ax_settable(element, attribute):
    """Returns `(err, is_settable)`."""
    return HIServices.AXUIElementIsAttributeSettable(element, attribute, None)


def _ax_app_element(pid):
    return HIServices.AXUIElementCreateApplication(pid)


def _modifier_flags() -> int:
    """Physically-held modifier flags, independent of events we synthesise."""
    return Quartz.CGEventSourceFlagsState(
        Quartz.kCGEventSourceStateCombinedSessionState
    )


def _post_paste_keystroke(pid: int | None) -> None:
    """Synthesise Cmd+V.

    When the target PID is known (captured at record start) the events go
    straight to it. A session-wide post lands wherever focus happens to be by
    the time the event is delivered, which is not necessarily where the user
    was speaking.
    """
    src = Quartz.CGEventSourceCreate(Quartz.kCGEventSourceStateHIDSystemState)
    v_down = Quartz.CGEventCreateKeyboardEvent(src, _V_KEYCODE, True)
    v_up = Quartz.CGEventCreateKeyboardEvent(src, _V_KEYCODE, False)
    Quartz.CGEventSetFlags(v_down, Quartz.kCGEventFlagMaskCommand)
    Quartz.CGEventSetFlags(v_up, Quartz.kCGEventFlagMaskCommand)

    if pid:
        Quartz.CGEventPostToPid(pid, v_down)
        time.sleep(0.01)
        Quartz.CGEventPostToPid(pid, v_up)
    else:
        Quartz.CGEventPost(Quartz.kCGAnnotatedSessionEventTap, v_down)
        Quartz.CGEventPost(Quartz.kCGAnnotatedSessionEventTap, v_up)


# --- focus tracking ---------------------------------------------------------


def capture_focus_target() -> dict | None:
    """Snapshot the app that should receive the transcription.

    Called when recording *starts*, not when it finishes: transcription takes
    seconds and the user often switches windows while it runs. Without this the
    text lands in whatever happens to be focused at paste time.

    Returns `{"pid": int, "name": str | None}`, or None if it can't be read.
    """
    try:
        app = _frontmost_app()
        if app is None:
            return None
        return {"pid": int(app.processIdentifier()), "name": app.localizedName()}
    except Exception:
        logging.debug("Focus capture failed", exc_info=True)
        return None


def _frontmost_pid() -> int | None:
    try:
        app = _frontmost_app()
        if app is None:
            return None
        return int(app.processIdentifier())
    except Exception:
        logging.debug("Frontmost PID lookup failed", exc_info=True)
        return None


def focus_target_is_active(target: dict | None) -> bool:
    """True if `target` (from `capture_focus_target`) is still frontmost.

    True when there's nothing to compare against — we stay optimistic and paste
    rather than silently dropping the user's dictation.
    """
    if not target:
        return True
    pid = _frontmost_pid()
    if pid is None:
        return True
    return pid == target.get("pid")


def _focused_element():
    """Return the focused AXUIElement, or None if it can't be read."""
    try:
        app = _frontmost_app()
        if app is None:
            return None
        err, focused = _ax_value(
            _ax_app_element(app.processIdentifier()), "AXFocusedUIElement"
        )
        if err != 0:
            return None
        return focused
    except Exception:
        logging.debug("Focused element lookup failed", exc_info=True)
        return None


def is_secure_field(focused=None) -> bool:
    """True if the focused element is a password field.

    Pasting a transcript there would leave it sitting in the clipboard (and in
    the history log), so we refuse outright.
    """
    try:
        if focused is None:
            focused = _focused_element()
        if focused is None:
            return False
        err, subrole = _ax_value(focused, "AXSubrole")
        if err != 0 or not subrole:
            return False
        return "secure" in str(subrole).lower()
    except Exception:
        logging.debug("Secure field detection failed", exc_info=True)
        return False


def _can_accept_paste(focused=None) -> bool:
    """Check if the focused element likely accepts text input.

    Returns True (optimistic) when:
    - AX query fails entirely (Electron apps, etc.) — assume paste works
    - Focused element has AXSelectedTextRange (has a cursor)
    - AXValue or AXSelectedText is settable
    - Role is not in the known non-text-input list

    Returns False only when we're confident there's no text input.
    """
    try:
        if focused is None:
            focused = _focused_element()
        if focused is None:
            # Can't read focused element (Electron apps, etc.)
            # Be optimistic — Cmd+V usually works in these apps
            return True

        # Check 1: does it have a text selection range? (most reliable positive signal)
        err2, _ = _ax_value(focused, "AXSelectedTextRange")
        if err2 == 0:
            return True

        # Check 2: is AXValue or AXSelectedText settable?
        err3, settable = _ax_settable(focused, "AXValue")
        if err3 == 0 and settable:
            return True

        err4, settable2 = _ax_settable(focused, "AXSelectedText")
        if err4 == 0 and settable2:
            return True

        # Check 3: is the role a known non-text role?
        err5, role = _ax_value(focused, "AXRole")
        if err5 == 0 and role in _NON_TEXT_ROLES:
            logging.info("Paste detection: non-text role %s — text left in clipboard", role)
            return False

        # Unknown situation — be optimistic
        return True
    except Exception:
        logging.debug("Paste detection failed", exc_info=True)
        return True  # optimistic on error


def wait_for_modifiers_released(timeout: float = 2.0, poll: float = 0.015) -> bool:
    """Block until no modifier keys are physically held, or `timeout` elapses.

    Sabbel pastes the moment the hotkey is released, but the user's hand is
    still leaving the keyboard. If Option (or anything else) is still down when
    we post Cmd+V, the target app sees Cmd+Opt+V: the paste silently does
    nothing, or fires some unrelated shortcut.

    Returns True if the modifiers cleared, False on timeout (the caller pastes
    anyway rather than dropping the transcription).
    """
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if not (_modifier_flags() & _MODIFIER_MASK):
            return True
        time.sleep(poll)
    logging.info("Modifiers still held after %.1fs — pasting anyway", timeout)
    return False


# --- pasteboard -------------------------------------------------------------


def _capture_pasteboard(pb) -> list[dict]:
    """Snapshot every item and every type on the pasteboard.

    Saving only the string flavour (the old behaviour) destroys images, rich
    text and file references: whatever the user had copied comes back as plain
    text, or not at all.
    """
    snapshot: list[dict] = []
    try:
        items = pb.pasteboardItems()
        if items is None:
            return snapshot
        for item in items:
            data_by_type = {}
            for type_ in item.types():
                data = item.dataForType_(type_)
                if data is not None:
                    data_by_type[type_] = data
            snapshot.append(data_by_type)
    except Exception:
        logging.debug("Pasteboard capture failed", exc_info=True)
    return snapshot


def _restore_pasteboard(pb, snapshot: list[dict]) -> None:
    """Rewrite a snapshot captured by `_capture_pasteboard`."""
    try:
        pb.clearContents()
        if not snapshot:
            return
        items = []
        for data_by_type in snapshot:
            item = _new_pasteboard_item()
            for type_, data in data_by_type.items():
                item.setData_forType_(data, type_)
            items.append(item)
        if items:
            pb.writeObjects_(items)
    except Exception:
        logging.exception("Pasteboard restore failed")


def _write_transient(pb, text: str) -> int:
    """Put `text` on the pasteboard tagged so clipboard managers skip it.

    Returns the resulting changeCount.
    """
    item = _new_pasteboard_item()
    item.setString_forType_(text, NSPasteboardTypeString)
    item.setData_forType_(b"", _TRANSIENT_TYPE)
    item.setData_forType_(b"", _AUTOGENERATED_TYPE)
    pb.clearContents()
    pb.writeObjects_([item])
    return pb.changeCount()


# --- paste verification -----------------------------------------------------


def _focused_value() -> str | None:
    """AXValue of the focused element, or None when unreadable."""
    focused = _focused_element()
    if focused is None:
        return None
    err, value = _ax_value(focused, "AXValue")
    if err != 0 or value is None:
        return None
    return str(value)


def _paste_landed(before: str | None, expected: str) -> bool:
    """Best-effort check that the focused field actually received the paste.

    Many apps (Electron, terminals) expose nothing useful here, which is why an
    inconclusive answer means "keep waiting, then fall back to a fixed delay"
    rather than "the paste failed".
    """
    value = _focused_value()
    if value is None:
        return False
    if before is not None and value == before:
        return False
    return expected in value


# --- main entry point -------------------------------------------------------


def inject_text(
    text: str,
    pre_paste_delay: float = 0.05,
    post_paste_delay: float = 0.15,
    target: dict | None = None,
    modifier_timeout: float = 2.0,
    verify_timeout: float = 2.0,
) -> str:
    """Paste text into the focused app via the clipboard and a synthetic Cmd+V.

    If a text input is detected (or detection is inconclusive), pastes and
    restores the previous clipboard. If we're confident there's no text input,
    pastes and leaves the transcribed text in the clipboard as a fallback.

    Returns one of PASTED, LEFT_IN_CLIPBOARD, FOCUS_CHANGED, REFUSED_SECURE.
    """
    if not focus_target_is_active(target):
        logging.info(
            "Focus changed since recording started (expected %s) — leaving text in clipboard",
            (target or {}).get("name"),
        )
        _write_transient(_general_pasteboard(), text)
        return FOCUS_CHANGED

    focused = _focused_element()
    if is_secure_field(focused):
        logging.info("Focused element is a secure text field — refusing to paste")
        return REFUSED_SECURE

    pb = _general_pasteboard()
    paste_likely = _can_accept_paste(focused)

    # Don't let a still-held Option turn our Cmd+V into Cmd+Opt+V.
    wait_for_modifiers_released(timeout=modifier_timeout)

    snapshot = _capture_pasteboard(pb)
    value_before = _focused_value()
    our_change_count = _write_transient(pb, text)

    # Wait for pasteboard sync
    time.sleep(pre_paste_delay)

    _post_paste_keystroke((target or {}).get("pid"))

    # Wait for the paste to actually land before touching the clipboard again.
    # A fixed 150ms is not enough for Slack/Ghostty/Electron; restoring too
    # early makes the app paste the *previous* clipboard contents instead.
    #
    # Only poll when the field is actually readable. Electron apps and
    # terminals expose no AXValue, so polling them would burn the full
    # verify_timeout on every single dictation — far worse than the fixed
    # delay it replaced.
    if value_before is None:
        time.sleep(post_paste_delay)
    else:
        deadline = time.monotonic() + verify_timeout
        landed = False
        while time.monotonic() < deadline:
            if _paste_landed(value_before, text):
                landed = True
                break
            time.sleep(0.02)
        if not landed:
            # The field was readable and the text never appeared, so the paste
            # genuinely failed. Restoring now would destroy the transcript —
            # leave it in the clipboard instead.
            logging.info("Paste not observed within %.1fs — leaving text in clipboard", verify_timeout)
            return LEFT_IN_CLIPBOARD

    # Did someone else touch the clipboard while we were pasting? (The user
    # copied something, or another app wrote to it.)
    if pb.changeCount() != our_change_count:
        if pb.stringForType_(NSPasteboardTypeString) != text:
            logging.info("Clipboard changed during paste — skipping restore")
            return PASTED

    if not paste_likely:
        # Leave text in clipboard as fallback
        return LEFT_IN_CLIPBOARD

    _restore_pasteboard(pb, snapshot)
    return PASTED
